# Generated by Django 5.1 on 2024-08-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['-name'], 'verbose_name': 'Mi depart', 'verbose_name_plural': 'Algunas Areas'},
        ),
    ]
